# -*- coding: utf-8 -*-
"""Copy of PotatoD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNl7-GSQG9rNSPegypwveDNQPOT-dhc_
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

import cv2
import matplotlib.pyplot as plt

# Load the RGB image
rgb_image = cv2.imread('/content/drive/MyDrive/Colab Notebooks/Data/Train/now/mildew grape/Copy of IMG_20201016_161616.jpg')

# Convert the RGB image to grayscale
gray_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2GRAY)

# Display the original RGB image
plt.imshow('Original RGB Image', rgb_image)
plt.waitKey(0)
plt.destroyAllWindows()

# Display the grayscale image
plt.imshow('Grayscale Image', gray_image)
plt.waitKey(0)
plt.destroyAllWindows()

# Save the grayscale image
plt.imwrite('output_grayscale_image.jpg', gray_image)

DATADIR = "/content/drive/MyDrive/Colab Notebooks/Data/Train/now"
CATEGORIES = ["mildew grape"] #"mildew grape","healthy grape","earlyp","latep"
i = 0
for category in CATEGORIES:
    path = os.path.join(DATADIR,category)
    for img in os.listdir(path):
        print(img)
        i=i+1
        if i==5:
           break
        img_array = cv2.imread( os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
        plt.imshow(img_array,cmap="gray")
        plt.show()
        #break
    break

print(img_array)

print(img_array.shape)

IMG_SIZE = 50

new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
plt.imshow(new_array, cmap='gray')
plt.show()

"""a bit blurry I'd say. Let's go with 100x100?


"""

new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
plt.imshow(new_array, cmap='gray')
plt.show()

training_data = []

def create_training_data():
    for category in CATEGORIES:  # do dogs and cats

        path = os.path.join(DATADIR,category)  # create path to dogs and cats
        class_num = CATEGORIES.index(category)  # get the classification  (0 or a 1). 0=dog 1=cat

        for img in tqdm(os.listdir(path)):  # iterate over each image per dogs and cats
            try:
                img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                training_data.append([new_array, class_num])  # add this to our training_data
            except Exception as e:  # in the interest in keeping the output clean...
                pass
            #except OSError as e:
            #    print("OSErrroBad img most likely", e, os.path.join(path,img))
            #except Exception as e:
            #    print("general exception", e, os.path.join(path,img))

create_training_data()

print(len(training_data))

import random

random.shuffle(training_data)
for sample in training_data[:10]:
    print(sample[1])

w1 = []
z1 = []

for features,label in training_data:
   w1.append(features)
   z1.append(label)

print(w1[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))

w1 = np.array(w1).reshape(-1, IMG_SIZE, IMG_SIZE, 1)

#save
import pickle

pickle_out = open("/content/drive/My Drive/Colab Notebooks/Thesis/w1.pickle","wb")
pickle.dump(w1, pickle_out)
pickle_out.close()

pickle_out = open("/content/drive/My Drive/Colab Notebooks/Thesis/z1.pickle","wb")
pickle.dump(z1, pickle_out)
pickle_out.close()

# For the current version:
!pip install --upgrade tensorflow

import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from keras.layers.advanced_activations import LeakyReLU
import pickle
import numpy as np

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/w1.pickle","rb")
w1 = pickle.load(pickle_in)

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/z1.pickle","rb")
z1 = pickle.load(pickle_in)

w1 = w1/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=w1.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(3, 3)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(3, 3)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(np.array(w1), np.array(z1), batch_size=32, epochs=3,verbose = 2, validation_split=0.3)

import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
# more info on callbakcs: https://keras.io/callbacks/ model saver is cool too.
from tensorflow.keras.callbacks import TensorBoard
import pickle
import time

NAME = "early-vs-latee"

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/w1.pickle","rb")
w1 = pickle.load(pickle_in)

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/z1.pickle","rb")
z1 = pickle.load(pickle_in)

w1 = w1/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=w1.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))

tensorboard = TensorBoard(log_dir="/content/drive/My Drive/Colab Notebooks/Thesis/errorr1/{}".format(NAME))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'],
              )
model.summary()
model.compile(loss='binary_crossentropy',  #logs/{}
              optimizer='adam',
              metrics=['accuracy'])

model.fit(np.array(w1), np.array(z1),  batch_size=32, epochs=3,verbose = 2, validation_split=0.3,
              callbacks=[tensorboard])

# Commented out IPython magic to ensure Python compatibility.
#And used:
#pip install --ignore-installed tf-nightly

#then:
#%load_ext tensorboard
#%tensorboard --logdir {logs_base_dir}


# %reload_ext tensorboard
# %tensorboard --logdir '/content/drive/My Drive/Colab Notebooks/Thesis/errorr1'

"""Update cnn small model 64"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
# more info on callbakcs: https://keras.io/callbacks/ model saver is cool too.
from tensorflow.keras.callbacks import TensorBoard
import pickle
import time

NAME = "early-vs-latx6"

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/w1.pickle","rb")
w1 = pickle.load(pickle_in)

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/z1.pickle","rb")
z1 = pickle.load(pickle_in)

w1 = w1/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=w1.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))
model.add(Activation('relu'))

model.add(Dense(1))
model.add(Activation('sigmoid'))

tensorboard = TensorBoard(log_dir="/content/drive/My Drive/Colab Notebooks/Thesis/errorr1/{}".format(NAME))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'],
              )
model.summary()

history = model.fit(np.array(w1), np.array(z1),  batch_size=32, epochs=10,verbose = 2, validation_split=0.3,
              callbacks=[tensorboard])

"""final update model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
# more info on callbakcs: https://keras.io/callbacks/ model saver is cool too.
from tensorflow.keras.callbacks import TensorBoard
import pickle
import time

NAME = "early-vs-latx6"

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/w1.pickle","rb")
w1 = pickle.load(pickle_in)

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/z1.pickle","rb")
z1 = pickle.load(pickle_in)

w1 = w1/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=w1.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))
model.add(Activation('relu'))

model.add(Dense(1))
model.add(Activation('sigmoid'))

tensorboard = TensorBoard(log_dir="/content/drive/My Drive/Colab Notebooks/Thesis/errorr1/{}".format(NAME))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'],
              )
model.summary()

history = model.fit(np.array(w1), np.array(z1),  batch_size=32, epochs=10,verbose = 2, validation_split=0.3,
              callbacks=[tensorboard])

# Commented out IPython magic to ensure Python compatibility.

# %reload_ext tensorboard
# %tensorboard --logdir '/content/drive/My Drive/Colab Notebooks/Thesis/errorr1'

print(history.history.keys())

import matplotlib. pyplot as plt
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1,len(acc) +1)
#train,vali acc

plt.plot(epochs,acc,'b',label='Training accuracy')
plt.plot(epochs,val_acc,'r',label='Validation accuracy')
plt.title('Train and Validation acc')
plt.legend()
plt.figure()

#train ,valid loss
plt.plot(epochs,loss,'b',label='Training loss')
plt.plot(epochs,val_loss,'r',label='Validation loss')
plt.title('Train and Validation loss')
plt.legend()
plt.figure()

"""#A simple for-loop will do! For example:

"""

import time

dense_layers = [0,1,2]
layer_sizes = [32, 64, 128]
conv_layers = [1, 2, 3]

for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for conv_layer in conv_layers:
            NAME = "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            print(NAME)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
# more info on callbakcs: https://keras.io/callbacks/ model saver is cool too.
from tensorflow.keras.callbacks import TensorBoard
import pickle
import time


pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/w1.pickle","rb")
w1 = pickle.load(pickle_in)

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/z1.pickle","rb")
z1 = pickle.load(pickle_in)

w1 = w1/255.0


dense_layers = [0, 1, 2]
layer_sizes = [ 64, 128,256]
conv_layers = [1, 2, 3]

for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for conv_layer in conv_layers:
            NAME = "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            print(NAME)

            model = Sequential()

            model.add(Conv2D(layer_size, (3, 3), input_shape=w1.shape[1:]))
            model.add(Activation('relu'))
            model.add(MaxPooling2D(pool_size=(2, 2)))

            for l in range(conv_layer-1):
                model.add(Conv2D(layer_size, (3, 3)))
                model.add(Activation('relu'))
                model.add(MaxPooling2D(pool_size=(2, 2)))

            model.add(Flatten())

            for _ in range(dense_layer):
                model.add(Dense(layer_size))
                model.add(Activation('relu'))

            model.add(Dense(1))
            model.add(Activation('sigmoid'))

            tensorboard = TensorBoard(log_dir="/content/drive/My Drive/Colab Notebooks/Thesis/errorr1/{}".format(NAME))

            model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'],
              )


            model.fit(np.array(w1), np.array(z1),  batch_size=32, epochs=3,verbose = 2, validation_split=0.3,
              callbacks=[tensorboard])

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext tensorboard
# %tensorboard --logdir '/content/drive/My Drive/Colab Notebooks/Thesis/errorr1'

'''from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
# more info on callbakcs: https://keras.io/callbacks/ model saver is cool too.
from tensorflow.keras.callbacks import TensorBoard
import pickle
import time

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/xo.pickle","rb")
xo = pickle.load(pickle_in)

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/yo.pickle","rb")
yo = pickle.load(pickle_in)

xo = xo/255.0

dense_layers = [1]
layer_sizes = [64]
conv_layers = [1]

for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for conv_layer in conv_layers:
            NAME = "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            print(NAME)

            model = Sequential()

            model.add(Conv2D(layer_size, (3, 3), input_shape=xo.shape[1:]))
            model.add(Activation('relu'))
            model.add(MaxPooling2D(pool_size=(5, 5)))

            for l in range(conv_layer-1):
                model.add(Conv2D(layer_size, (3, 3)))
                model.add(Activation('relu'))
                model.add(MaxPooling2D(pool_size=(5, 5)))

            model.add(Flatten())

            for _ in range(dense_layer):
                model.add(Dense(layer_size))
                model.add(Activation('relu'))

            model.add(Dense(1))
            model.add(Activation('sigmoid'))

            tensorboard = TensorBoard(log_dir="/content/drive/My Drive/Colab Notebooks/Thesis/ear3/{}".format(NAME))

            model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'],
              )
            model.summary()

            model.fit(np.array(xo), np.array(yo),  batch_size=32, epochs=30,verbose = 2, validation_split=0.3,
              callbacks=[tensorboard])
model.save('/content/drive/My Drive/Colab Notebooks/Thesis/ear3/1641x2-CNN.model')

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
# more info on callbakcs: https://keras.io/callbacks/ model saver is cool too.
from tensorflow.keras.callbacks import TensorBoard
import pickle
import time
#from keras.layers.normalization import BatchNormalization
pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/w1.pickle","rb")
w1 = pickle.load(pickle_in)

pickle_in = open("/content/drive/My Drive/Colab Notebooks/Thesis/z1.pickle","rb")
z1 = pickle.load(pickle_in)

w1 = w1/255.0


dense_layers = [2]#[2] #[1,2] #0  0
layer_sizes = [256]#[64] #[64,128] #32  64
conv_layers = [1]#[1] #[1,2]  #3   3

#hidden_units_number=128
#l2_lambda = .001
#dropout = 0.5
#initialization = 'lecun_uniform'

for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for conv_layer in conv_layers:
            NAME = "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            print(NAME)

            model = Sequential()

            #this for input layer
            model.add(Conv2D(layer_size, (3, 3),padding='same', input_shape=w1.shape[1:]))#input_shape=xx.shape[1:]
            #model.add(new BatchNormalization(hidden_units_number))
            model.add(Dense(64, use_bias=False))
            model.add(tf.keras.layers.BatchNormalization())
            model.add(tf.keras.layers.LeakyReLU(alpha=0.3))#model.add(Activation('relu')) #model.add(Activation('tanh'))#
            model.add(MaxPooling2D(pool_size=(5, 5)))
            model.add(Dropout(.25))
            #for hidden
            for l in range(conv_layer-1):
                model.add(Conv2D(layer_size, (3, 3),padding='same'))
                model.add(Dense(64, use_bias=False))
                model.add(tf.keras.layers.BatchNormalization())
                model.add(tf.keras.layers.LeakyReLU(alpha=0.3))#model.add(Activation('relu')) #model.add(Activation('tanh'))#
                model.add(tf.keras.layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
                                                          beta_initializer='zeros', gamma_initializer='ones', moving_mean_initializer='zeros',

                               moving_variance_initializer='ones', beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None))
                model.add(MaxPooling2D(pool_size=(5, 5)))#output layer
                model.add(Dropout(.25))

            model.add(Flatten())

            for _ in range(dense_layer):
                #model.add(Dense(512))
                model.add(Dense(1024, use_bias=False))
                model.add(tf.keras.layers.BatchNormalization())
                model.add(tf.keras.layers.LeakyReLU(alpha=0.3))#model.add(Activation('relu')) #model.add(Activation('tanh'))
                model.add(Dropout(0.5))

            model.add(Dense(1))
            model.add(Activation('sigmoid'))#sigmoid softmax

            tensorboard = TensorBoard(log_dir="/content/drive/My Drive/Colab Notebooks/Thesis/error1/{}".format(NAME))

            # setting up the optimization of our weights
            #sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
            adam = tf.keras.optimizers.Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, amsgrad=False)
            model.compile(loss='binary_crossentropy',
                          optimizer=adam, #optimizer='adam'
                          metrics=['accuracy'],
                          )

            model.fit(np.array(w1), np.array(z1),
                      batch_size=32,#batch_size=32
                      epochs=20,
                      validation_split=0.3,#.3#.2  (.2 jnno)
                      verbose = 2,
                      callbacks=[tensorboard])
            model.save('/content/drive/My Drive/Colab Notebooks/Thesis/errorr1/12562-CNN.model')

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext tensorboard
# %tensorboard --logdir '/content/drive/My Drive/Colab Notebooks/Thesis/errorr1'

import cv2
import tensorflow as tf

CATEGORIES = ["Potato_Early_blight", "Potato_Late_blight"]  # will use this to convert prediction num to string value


def prepare(filepath):
    IMG_SIZE = 70  # 50 in txt-based
    img_array = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)  # read in the image, convert to grayscale
    #img_array=img_array/255
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize image to match model's expected sizing
    return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 1)  # return the image with shaping that TF wants.
model = tf.keras.models.load_model("/content/drive/My Drive/Colab Notebooks/Thesis/errorr1/12562-CNN.model")#1641-CNN.model

prediction = model.predict([prepare('/content/drive/MyDrive/Colab Notebooks/Data/validation/Potato_Early_blight/IMG00011_0_103.jpg')])
print(prediction)  # will be a list in a list.
print(CATEGORIES[int(prediction[0][0])])

prediction = model.predict([prepare('/content/drive/MyDrive/Colab Notebooks/Data/validation/Potato_Late_blight/202001219_193155.jpg')])
print(prediction)  # will be a list in a list.
print(CATEGORIES[int(prediction[0][0])])